In [36]:
import numpy as np

In [16]:
my_array = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [43]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [28]:
my_array[my_array < 0]

array([-2, -1, -6, -7])

In [44]:
num_negatives = len(my_array[my_array < 0])
print("Number of negative numbers:", num_negatives)

Number of negative numbers: 2


In [31]:
num_positives = len(my_array[my_array < 0])
print(num_positives)

4


In [45]:
len(a[a>0])

5

In [33]:
positive_nums = my_array[my_array > 0] # filter for positive numbers
even_nums = positive_nums[positive_nums % 2 == 0] # filter for even numbers
print(len(even_nums))

3


In [47]:
pos_nums = a[a>0]
len(pos_nums[pos_nums % 2 == 0])

3

In [34]:
my_array = my_array + 3
positive_nums = my_array[my_array > 0]
print(positive_nums)

[ 7 13 15 26  1  2  3  3  3  6]


In [ ]:
np.sqrt(arr)

In [38]:
sqrt_array = np.sqrt(my_array) # square root the array

new_mean = np.mean(sqrt_array) # calculate the new mean

new_std = np.std(sqrt_array) # calculate the new standard deviation

print("Square root of my_array:", sqrt_array)
print("New mean:", new_mean)
print("New standard deviation:", new_std) 

Square root of my_array: [2.64575131 3.60555128 3.87298335 5.09901951 1.         1.41421356
 1.73205081 1.73205081 1.73205081        nan 2.44948974        nan]
New mean: nan
New standard deviation: nan


/var/folders/cq/k4_shrmd3jqcmhl3902xm04r0000gn/T/ipykernel_86088/952676804.py:1: RuntimeWarning: invalid value encountered in sqrt
  sqrt_array = np.sqrt(my_array) # square root the array


In [48]:
a_squared = a ** 2
a_squared.mean()

74.0

In [49]:
a_squared.std()

144.0243035046516

In [39]:
mean = np.mean(my_array) # Calculate the mean of the array

centered_array = my_array - mean # Subtract the mean from each element in the array

print("Original array:", my_array)
print("Centered array:", centered_array)

Original array: [ 7 13 15 26  1  2  3  3  3 -3  6 -4]
Centered array: [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [50]:
centered_a = a - a.mean()

In [51]:
centered_a.mean()

0.0

In [42]:
mean = np.mean(my_array) # First, we need to calculate the mean and standard deviation of the array:
std_dev = np.std(my_array)

# The mean of `my_array` is `3.0` and the standard deviation is `8.06225774829855`.

z = (x_i - mean) / std_dev


z_scores = [(x - mean) / std_dev for x in my_array]
print(z_scores)

SyntaxError: invalid syntax (2162463767.py, line 7)

In [52]:
z_scores = centered_a / a.std()

In [53]:
z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])