In [16]:
import numpy as np

In [16]:
my_array = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [43]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [28]:
my_array[my_array < 0]

array([-2, -1, -6, -7])

In [44]:
num_negatives = len(my_array[my_array < 0])
print("Number of negative numbers:", num_negatives)

Number of negative numbers: 2


In [31]:
num_positives = len(my_array[my_array < 0])
print(num_positives)

4


In [45]:
len(a[a>0])

5

In [33]:
positive_nums = my_array[my_array > 0] # filter for positive numbers
even_nums = positive_nums[positive_nums % 2 == 0] # filter for even numbers
print(len(even_nums))

3


In [47]:
pos_nums = a[a>0]
len(pos_nums[pos_nums % 2 == 0])

3

In [34]:
my_array = my_array + 3
positive_nums = my_array[my_array > 0]
print(positive_nums)

[ 7 13 15 26  1  2  3  3  3  6]


In [ ]:
np.sqrt(arr)

In [38]:
sqrt_array = np.sqrt(my_array) # square root the array

new_mean = np.mean(sqrt_array) # calculate the new mean

new_std = np.std(sqrt_array) # calculate the new standard deviation

print("Square root of my_array:", sqrt_array)
print("New mean:", new_mean)
print("New standard deviation:", new_std) 

Square root of my_array: [2.64575131 3.60555128 3.87298335 5.09901951 1.         1.41421356
 1.73205081 1.73205081 1.73205081        nan 2.44948974        nan]
New mean: nan
New standard deviation: nan


/var/folders/cq/k4_shrmd3jqcmhl3902xm04r0000gn/T/ipykernel_86088/952676804.py:1: RuntimeWarning: invalid value encountered in sqrt
  sqrt_array = np.sqrt(my_array) # square root the array


In [48]:
a_squared = a ** 2
a_squared.mean()

74.0

In [49]:
a_squared.std()

144.0243035046516

In [39]:
mean = np.mean(my_array) # Calculate the mean of the array

centered_array = my_array - mean # Subtract the mean from each element in the array

print("Original array:", my_array)
print("Centered array:", centered_array)

Original array: [ 7 13 15 26  1  2  3  3  3 -3  6 -4]
Centered array: [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [50]:
centered_a = a - a.mean()

In [51]:
centered_a.mean()

0.0

In [42]:
mean = np.mean(my_array) # First, we need to calculate the mean and standard deviation of the array:
std_dev = np.std(my_array)

# The mean of `my_array` is `3.0` and the standard deviation is `8.06225774829855`.

z = (x_i - mean) / std_dev


z_scores = [(x - mean) / std_dev for x in my_array]
print(z_scores)

SyntaxError: invalid syntax (2162463767.py, line 7)

In [52]:
z_scores = centered_a / a.std()

In [53]:
z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

Use the more numpy practice link and follow the questions within it.

Setup 1

In [1]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Use python's built in functionality/operators to determine the following:

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [2]:
type(a)

list

In [3]:
sum(a)

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [4]:
min(a)

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [5]:
max(a)

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [6]:
sum(a) / len(a)

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [7]:
prod_a = 1
for n in a:
    prod_a *= n

In [8]:
prod_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [9]:
[n ** 2 for n in a]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [10]:
[n for n in a if n % 2 != 0]

[1, 3, 5, 7, 9]

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [11]:
[n for n in a if n % 2 == 0]

[2, 4, 6, 8, 10]

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [17]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b2 = np.array(b)

In [13]:
b

[[3, 4, 5], [6, 7, 8]]

In [18]:
b2

array([[3, 4, 5],
       [6, 7, 8]])

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. Hint, you'll first need to make sure that the "b" variable is a numpy array

In [20]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [21]:
sum_of_b

33

In [22]:
b2.sum()

33

Exercise 2 - refactor the following to use numpy.

In [23]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [24]:
min_of_b

3

In [25]:
b2.min()

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [26]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [27]:
max_of_b

8

In [28]:
b2.max()

8

Exercise 4 - refactor the following using numpy to find the mean of b

In [29]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [30]:
mean_of_b

5.5

In [31]:
b2.mean()

5.5

Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [32]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [33]:
product_of_b

20160

In [34]:
b2.prod()

20160

In [35]:
np.prod(b2)

20160

Exercise 6 - refactor the following to use numpy to find the list of squares

In [36]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [37]:
squares_of_b

[9, 16, 25, 36, 49, 64]

In [38]:
np.square(b2)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [39]:
b2 ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

Exercise 7 - refactor using numpy to determine the odds_in_b

In [40]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [41]:
odds_in_b

[3, 5, 7]

In [42]:
b2[b2 % 2 != 0]

array([3, 5, 7])

Exercise 9 - print out the shape of the array b.

In [43]:
b2.shape

(2, 3)

Exercise 10 - transpose the array b.

In [44]:
b2

array([[3, 4, 5],
       [6, 7, 8]])

In [46]:
b2.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [47]:
b2.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [48]:
b2.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

Setup 3

In [49]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [50]:
c = np.array(c)

Exercise 1 - Find the min, max, sum, and product of c.

In [51]:
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

Exercise 2 - Determine the standard deviation of c.

In [52]:
c.std()

2.581988897471611

Exercise 3 - Determine the variance of c.

In [53]:
c.var()

6.666666666666667

Exercise 4 - Print out the shape of the array c

In [54]:
c.shape

(3, 3)

Exercise 5 - Transpose c and print out transposed result.

In [55]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Exercise 6 - Get the dot product of the array c with c.

In [56]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [57]:
np.sum(c * c.transpose())

261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [58]:
np.prod(c * c.transpose())

131681894400

Setup 4

In [59]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

Exercise 1 - Find the sine of all the numbers in d

In [60]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d

In [61]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d

In [62]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4 - Find all the negative numbers in d

In [63]:
d[d < 0]

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d

In [64]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d.

In [65]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.

In [66]:
len(np.unique(d))

11

Exercise 8 - Print out the shape of d.

In [67]:
d.shape

(3, 6)

Exercise 9 - Transpose and then print out the shape of d.

In [68]:
d.transpose().shape

(6, 3)

Exercise 10 - Reshape d into an array of 9 x 2

In [69]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])